// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/membership.proto

package model;

public final class Membership {
  private Membership() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MemberInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MemberInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string host = 1;</code>
     * @return The host.
     */
    java.lang.String getHost();
    /**
     * <code>string host = 1;</code>
     * @return The bytes for host.
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <code>int32 port = 2;</code>
     * @return The port.
     */
    int getPort();

    /**
     * <code>int32 id = 3;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>bool isLeader = 4;</code>
     * @return The isLeader.
     */
    boolean getIsLeader();

    /**
     * <code>string state = 5;</code>
     * @return The state.
     */
    java.lang.String getState();
    /**
     * <code>string state = 5;</code>
     * @return The bytes for state.
     */
    com.google.protobuf.ByteString
        getStateBytes();

    /**
     * <code>string leaderHost = 6;</code>
     * @return The leaderHost.
     */
    java.lang.String getLeaderHost();
    /**
     * <code>string leaderHost = 6;</code>
     * @return The bytes for leaderHost.
     */
    com.google.protobuf.ByteString
        getLeaderHostBytes();

    /**
     * <code>int32 leaderPort = 7;</code>
     * @return The leaderPort.
     */
    int getLeaderPort();

    /**
     * <code>bool isAlive = 8;</code>
     * @return The isAlive.
     */
    boolean getIsAlive();

    /**
     * <code>.MemberInfo.srcType type = 9;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.MemberInfo.srcType type = 9;</code>
     * @return The type.
     */
    model.Membership.MemberInfo.srcType getType();

    /**
     * <code>map&lt;int32, .BrokerInfo&gt; membershipTable = 10;</code>
     */
    int getMembershipTableCount();
    /**
     * <code>map&lt;int32, .BrokerInfo&gt; membershipTable = 10;</code>
     */
    boolean containsMembershipTable(
        int key);
    /**
     * Use {@link #getMembershipTableMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, model.Membership.BrokerInfo>
    getMembershipTable();
    /**
     * <code>map&lt;int32, .BrokerInfo&gt; membershipTable = 10;</code>
     */
    java.util.Map<java.lang.Integer, model.Membership.BrokerInfo>
    getMembershipTableMap();
    /**
     * <code>map&lt;int32, .BrokerInfo&gt; membershipTable = 10;</code>
     */

    model.Membership.BrokerInfo getMembershipTableOrDefault(
        int key,
        model.Membership.BrokerInfo defaultValue);
    /**
     * <code>map&lt;int32, .BrokerInfo&gt; membershipTable = 10;</code>
     */

    model.Membership.BrokerInfo getMembershipTableOrThrow(
        int key);

    /**
     * <code>int32 version = 11;</code>
     * @return The version.
     */
    int getVersion();
  }
  /**
   * Protobuf type {@code MemberInfo}
   */
  public static final class MemberInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MemberInfo)
      MemberInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MemberInfo.newBuilder() to construct.
    private MemberInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MemberInfo() {
      host_ = "";
      state_ = "";
      leaderHost_ = "";
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MemberInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MemberInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 16: {

              port_ = input.readInt32();
              break;
            }
            case 24: {

              id_ = input.readInt32();
              break;
            }
            case 32: {

              isLeader_ = input.readBool();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              state_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              leaderHost_ = s;
              break;
            }
            case 56: {

              leaderPort_ = input.readInt32();
              break;
            }
            case 64: {

              isAlive_ = input.readBool();
              break;
            }
            case 72: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 82: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                membershipTable_ = com.google.protobuf.MapField.newMapField(
                    MembershipTableDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, model.Membership.BrokerInfo>
              membershipTable__ = input.readMessage(
                  MembershipTableDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              membershipTable_.getMutableMap().put(
                  membershipTable__.getKey(), membershipTable__.getValue());
              break;
            }
            case 88: {

              version_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return model.Membership.internal_static_MemberInfo_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 10:
          return internalGetMembershipTable();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return model.Membership.internal_static_MemberInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              model.Membership.MemberInfo.class, model.Membership.MemberInfo.Builder.class);
    }

    /**
     * Protobuf enum {@code MemberInfo.srcType}
     */
    public enum srcType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PRODUCER = 0;</code>
       */
      PRODUCER(0),
      /**
       * <code>BROKER = 1;</code>
       */
      BROKER(1),
      /**
       * <code>CONSUMER = 2;</code>
       */
      CONSUMER(2),
      /**
       * <code>LOADBALANCER = 3;</code>
       */
      LOADBALANCER(3),
      /**
       * <code>CONSUMER_FOLLOWER = 4;</code>
       */
      CONSUMER_FOLLOWER(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>PRODUCER = 0;</code>
       */
      public static final int PRODUCER_VALUE = 0;
      /**
       * <code>BROKER = 1;</code>
       */
      public static final int BROKER_VALUE = 1;
      /**
       * <code>CONSUMER = 2;</code>
       */
      public static final int CONSUMER_VALUE = 2;
      /**
       * <code>LOADBALANCER = 3;</code>
       */
      public static final int LOADBALANCER_VALUE = 3;
      /**
       * <code>CONSUMER_FOLLOWER = 4;</code>
       */
      public static final int CONSUMER_FOLLOWER_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static srcType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static srcType forNumber(int value) {
        switch (value) {
          case 0: return PRODUCER;
          case 1: return BROKER;
          case 2: return CONSUMER;
          case 3: return LOADBALANCER;
          case 4: return CONSUMER_FOLLOWER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<srcType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          srcType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<srcType>() {
              public srcType findValueByNumber(int number) {
                return srcType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return model.Membership.MemberInfo.getDescriptor().getEnumTypes().get(0);
      }

      private static final srcType[] VALUES = values();

      public static srcType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private srcType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MemberInfo.srcType)
    }

    public static final int HOST_FIELD_NUMBER = 1;
    private volatile java.lang.Object host_;
    /**
     * <code>string host = 1;</code>
     * @return The host.
     */
    @java.lang.Override
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <code>string host = 1;</code>
     * @return The bytes for host.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <code>int32 port = 2;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }

    public static final int ID_FIELD_NUMBER = 3;
    private int id_;
    /**
     * <code>int32 id = 3;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int ISLEADER_FIELD_NUMBER = 4;
    private boolean isLeader_;
    /**
     * <code>bool isLeader = 4;</code>
     * @return The isLeader.
     */
    @java.lang.Override
    public boolean getIsLeader() {
      return isLeader_;
    }

    public static final int STATE_FIELD_NUMBER = 5;
    private volatile java.lang.Object state_;
    /**
     * <code>string state = 5;</code>
     * @return The state.
     */
    @java.lang.Override
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        state_ = s;
        return s;
      }
    }
    /**
     * <code>string state = 5;</code>
     * @return The bytes for state.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEADERHOST_FIELD_NUMBER = 6;
    private volatile java.lang.Object leaderHost_;
    /**
     * <code>string leaderHost = 6;</code>
     * @return The leaderHost.
     */
    @java.lang.Override
    public java.lang.String getLeaderHost() {
      java.lang.Object ref = leaderHost_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        leaderHost_ = s;
        return s;
      }
    }
    /**
     * <code>string leaderHost = 6;</code>
     * @return The bytes for leaderHost.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLeaderHostBytes() {
      java.lang.Object ref = leaderHost_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leaderHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEADERPORT_FIELD_NUMBER = 7;
    private int leaderPort_;
    /**
     * <code>int32 leaderPort = 7;</code>
     * @return The leaderPort.
     */
    @java.lang.Override
    public int getLeaderPort() {
      return leaderPort_;
    }

    public static final int ISALIVE_FIELD_NUMBER = 8;
    private boolean isAlive_;
    /**
     * <code>bool isAlive = 8;</code>
     * @return The isAlive.
     */
    @java.lang.Override
    public boolean getIsAlive() {
      return isAlive_;
    }

    public static final int TYPE_FIELD_NUMBER = 9;
    private int type_;
    /**
     * <code>.MemberInfo.srcType type = 9;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.MemberInfo.srcType type = 9;</code>
     * @return The type.
     */
    @java.lang.Override public model.Membership.MemberInfo.srcType getType() {
      @SuppressWarnings("deprecation")
      model.Membership.MemberInfo.srcType result = model.Membership.MemberInfo.srcType.valueOf(type_);
      return result == null ? model.Membership.MemberInfo.srcType.UNRECOGNIZED : result;
    }

    public static final int MEMBERSHIPTABLE_FIELD_NUMBER = 10;
    private static final class MembershipTableDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, model.Membership.BrokerInfo> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, model.Membership.BrokerInfo>newDefaultInstance(
                  model.Membership.internal_static_MemberInfo_MembershipTableEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  model.Membership.BrokerInfo.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, model.Membership.BrokerInfo> membershipTable_;
    private com.google.protobuf.MapField<java.lang.Integer, model.Membership.BrokerInfo>
    internalGetMembershipTable() {
      if (membershipTable_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MembershipTableDefaultEntryHolder.defaultEntry);
      }
      return membershipTable_;
    }

    public int getMembershipTableCount() {
      return internalGetMembershipTable().getMap().size();
    }
    /**
     * <code>map&lt;int32, .BrokerInfo&gt; membershipTable = 10;</code>
     */

    @java.lang.Override
    public boolean containsMembershipTable(
        int key) {
      
      return internalGetMembershipTable().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMembershipTableMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, model.Membership.BrokerInfo> getMembershipTable() {
      return getMembershipTableMap();
    }
    /**
     * <code>map&lt;int32, .BrokerInfo&gt; membershipTable = 10;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Integer, model.Membership.BrokerInfo> getMembershipTableMap() {
      return internalGetMembershipTable().getMap();
    }
    /**
     * <code>map&lt;int32, .BrokerInfo&gt; membershipTable = 10;</code>
     */
    @java.lang.Override

    public model.Membership.BrokerInfo getMembershipTableOrDefault(
        int key,
        model.Membership.BrokerInfo defaultValue) {
      
      java.util.Map<java.lang.Integer, model.Membership.BrokerInfo> map =
          internalGetMembershipTable().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, .BrokerInfo&gt; membershipTable = 10;</code>
     */
    @java.lang.Override

    public model.Membership.BrokerInfo getMembershipTableOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, model.Membership.BrokerInfo> map =
          internalGetMembershipTable().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int VERSION_FIELD_NUMBER = 11;
    private int version_;
    /**
     * <code>int32 version = 11;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(host_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, host_);
      }
      if (port_ != 0) {
        output.writeInt32(2, port_);
      }
      if (id_ != 0) {
        output.writeInt32(3, id_);
      }
      if (isLeader_ != false) {
        output.writeBool(4, isLeader_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(state_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, state_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(leaderHost_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, leaderHost_);
      }
      if (leaderPort_ != 0) {
        output.writeInt32(7, leaderPort_);
      }
      if (isAlive_ != false) {
        output.writeBool(8, isAlive_);
      }
      if (type_ != model.Membership.MemberInfo.srcType.PRODUCER.getNumber()) {
        output.writeEnum(9, type_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetMembershipTable(),
          MembershipTableDefaultEntryHolder.defaultEntry,
          10);
      if (version_ != 0) {
        output.writeInt32(11, version_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(host_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, host_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, port_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, id_);
      }
      if (isLeader_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isLeader_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(state_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, state_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(leaderHost_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, leaderHost_);
      }
      if (leaderPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, leaderPort_);
      }
      if (isAlive_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, isAlive_);
      }
      if (type_ != model.Membership.MemberInfo.srcType.PRODUCER.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(9, type_);
      }
      for (java.util.Map.Entry<java.lang.Integer, model.Membership.BrokerInfo> entry
           : internalGetMembershipTable().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, model.Membership.BrokerInfo>
        membershipTable__ = MembershipTableDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(10, membershipTable__);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, version_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof model.Membership.MemberInfo)) {
        return super.equals(obj);
      }
      model.Membership.MemberInfo other = (model.Membership.MemberInfo) obj;

      if (!getHost()
          .equals(other.getHost())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (getId()
          != other.getId()) return false;
      if (getIsLeader()
          != other.getIsLeader()) return false;
      if (!getState()
          .equals(other.getState())) return false;
      if (!getLeaderHost()
          .equals(other.getLeaderHost())) return false;
      if (getLeaderPort()
          != other.getLeaderPort()) return false;
      if (getIsAlive()
          != other.getIsAlive()) return false;
      if (type_ != other.type_) return false;
      if (!internalGetMembershipTable().equals(
          other.internalGetMembershipTable())) return false;
      if (getVersion()
          != other.getVersion()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + ISLEADER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsLeader());
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState().hashCode();
      hash = (37 * hash) + LEADERHOST_FIELD_NUMBER;
      hash = (53 * hash) + getLeaderHost().hashCode();
      hash = (37 * hash) + LEADERPORT_FIELD_NUMBER;
      hash = (53 * hash) + getLeaderPort();
      hash = (37 * hash) + ISALIVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsAlive());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (!internalGetMembershipTable().getMap().isEmpty()) {
        hash = (37 * hash) + MEMBERSHIPTABLE_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMembershipTable().hashCode();
      }
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static model.Membership.MemberInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.Membership.MemberInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.Membership.MemberInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.Membership.MemberInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.Membership.MemberInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.Membership.MemberInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.Membership.MemberInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.Membership.MemberInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static model.Membership.MemberInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static model.Membership.MemberInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static model.Membership.MemberInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.Membership.MemberInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(model.Membership.MemberInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MemberInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MemberInfo)
        model.Membership.MemberInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return model.Membership.internal_static_MemberInfo_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 10:
            return internalGetMembershipTable();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 10:
            return internalGetMutableMembershipTable();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return model.Membership.internal_static_MemberInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                model.Membership.MemberInfo.class, model.Membership.MemberInfo.Builder.class);
      }

      // Construct using model.Membership.MemberInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        host_ = "";

        port_ = 0;

        id_ = 0;

        isLeader_ = false;

        state_ = "";

        leaderHost_ = "";

        leaderPort_ = 0;

        isAlive_ = false;

        type_ = 0;

        internalGetMutableMembershipTable().clear();
        version_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return model.Membership.internal_static_MemberInfo_descriptor;
      }

      @java.lang.Override
      public model.Membership.MemberInfo getDefaultInstanceForType() {
        return model.Membership.MemberInfo.getDefaultInstance();
      }

      @java.lang.Override
      public model.Membership.MemberInfo build() {
        model.Membership.MemberInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public model.Membership.MemberInfo buildPartial() {
        model.Membership.MemberInfo result = new model.Membership.MemberInfo(this);
        int from_bitField0_ = bitField0_;
        result.host_ = host_;
        result.port_ = port_;
        result.id_ = id_;
        result.isLeader_ = isLeader_;
        result.state_ = state_;
        result.leaderHost_ = leaderHost_;
        result.leaderPort_ = leaderPort_;
        result.isAlive_ = isAlive_;
        result.type_ = type_;
        result.membershipTable_ = internalGetMembershipTable();
        result.membershipTable_.makeImmutable();
        result.version_ = version_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof model.Membership.MemberInfo) {
          return mergeFrom((model.Membership.MemberInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(model.Membership.MemberInfo other) {
        if (other == model.Membership.MemberInfo.getDefaultInstance()) return this;
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getIsLeader() != false) {
          setIsLeader(other.getIsLeader());
        }
        if (!other.getState().isEmpty()) {
          state_ = other.state_;
          onChanged();
        }
        if (!other.getLeaderHost().isEmpty()) {
          leaderHost_ = other.leaderHost_;
          onChanged();
        }
        if (other.getLeaderPort() != 0) {
          setLeaderPort(other.getLeaderPort());
        }
        if (other.getIsAlive() != false) {
          setIsAlive(other.getIsAlive());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        internalGetMutableMembershipTable().mergeFrom(
            other.internalGetMembershipTable());
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        model.Membership.MemberInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (model.Membership.MemberInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object host_ = "";
      /**
       * <code>string host = 1;</code>
       * @return The host.
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string host = 1;</code>
       * @return The bytes for host.
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string host = 1;</code>
       * @param value The host to set.
       * @return This builder for chaining.
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string host = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>string host = 1;</code>
       * @param value The bytes for host to set.
       * @return This builder for chaining.
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 2;</code>
       * @return The port.
       */
      @java.lang.Override
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 2;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 3;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 3;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private boolean isLeader_ ;
      /**
       * <code>bool isLeader = 4;</code>
       * @return The isLeader.
       */
      @java.lang.Override
      public boolean getIsLeader() {
        return isLeader_;
      }
      /**
       * <code>bool isLeader = 4;</code>
       * @param value The isLeader to set.
       * @return This builder for chaining.
       */
      public Builder setIsLeader(boolean value) {
        
        isLeader_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isLeader = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsLeader() {
        
        isLeader_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object state_ = "";
      /**
       * <code>string state = 5;</code>
       * @return The state.
       */
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          state_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string state = 5;</code>
       * @return The bytes for state.
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string state = 5;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string state = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        
        state_ = getDefaultInstance().getState();
        onChanged();
        return this;
      }
      /**
       * <code>string state = 5;</code>
       * @param value The bytes for state to set.
       * @return This builder for chaining.
       */
      public Builder setStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        state_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object leaderHost_ = "";
      /**
       * <code>string leaderHost = 6;</code>
       * @return The leaderHost.
       */
      public java.lang.String getLeaderHost() {
        java.lang.Object ref = leaderHost_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          leaderHost_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string leaderHost = 6;</code>
       * @return The bytes for leaderHost.
       */
      public com.google.protobuf.ByteString
          getLeaderHostBytes() {
        java.lang.Object ref = leaderHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          leaderHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string leaderHost = 6;</code>
       * @param value The leaderHost to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        leaderHost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string leaderHost = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeaderHost() {
        
        leaderHost_ = getDefaultInstance().getLeaderHost();
        onChanged();
        return this;
      }
      /**
       * <code>string leaderHost = 6;</code>
       * @param value The bytes for leaderHost to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        leaderHost_ = value;
        onChanged();
        return this;
      }

      private int leaderPort_ ;
      /**
       * <code>int32 leaderPort = 7;</code>
       * @return The leaderPort.
       */
      @java.lang.Override
      public int getLeaderPort() {
        return leaderPort_;
      }
      /**
       * <code>int32 leaderPort = 7;</code>
       * @param value The leaderPort to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderPort(int value) {
        
        leaderPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 leaderPort = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeaderPort() {
        
        leaderPort_ = 0;
        onChanged();
        return this;
      }

      private boolean isAlive_ ;
      /**
       * <code>bool isAlive = 8;</code>
       * @return The isAlive.
       */
      @java.lang.Override
      public boolean getIsAlive() {
        return isAlive_;
      }
      /**
       * <code>bool isAlive = 8;</code>
       * @param value The isAlive to set.
       * @return This builder for chaining.
       */
      public Builder setIsAlive(boolean value) {
        
        isAlive_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isAlive = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsAlive() {
        
        isAlive_ = false;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.MemberInfo.srcType type = 9;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.MemberInfo.srcType type = 9;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MemberInfo.srcType type = 9;</code>
       * @return The type.
       */
      @java.lang.Override
      public model.Membership.MemberInfo.srcType getType() {
        @SuppressWarnings("deprecation")
        model.Membership.MemberInfo.srcType result = model.Membership.MemberInfo.srcType.valueOf(type_);
        return result == null ? model.Membership.MemberInfo.srcType.UNRECOGNIZED : result;
      }
      /**
       * <code>.MemberInfo.srcType type = 9;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(model.Membership.MemberInfo.srcType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MemberInfo.srcType type = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, model.Membership.BrokerInfo> membershipTable_;
      private com.google.protobuf.MapField<java.lang.Integer, model.Membership.BrokerInfo>
      internalGetMembershipTable() {
        if (membershipTable_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MembershipTableDefaultEntryHolder.defaultEntry);
        }
        return membershipTable_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, model.Membership.BrokerInfo>
      internalGetMutableMembershipTable() {
        onChanged();;
        if (membershipTable_ == null) {
          membershipTable_ = com.google.protobuf.MapField.newMapField(
              MembershipTableDefaultEntryHolder.defaultEntry);
        }
        if (!membershipTable_.isMutable()) {
          membershipTable_ = membershipTable_.copy();
        }
        return membershipTable_;
      }

      public int getMembershipTableCount() {
        return internalGetMembershipTable().getMap().size();
      }
      /**
       * <code>map&lt;int32, .BrokerInfo&gt; membershipTable = 10;</code>
       */

      @java.lang.Override
      public boolean containsMembershipTable(
          int key) {
        
        return internalGetMembershipTable().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMembershipTableMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, model.Membership.BrokerInfo> getMembershipTable() {
        return getMembershipTableMap();
      }
      /**
       * <code>map&lt;int32, .BrokerInfo&gt; membershipTable = 10;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.Integer, model.Membership.BrokerInfo> getMembershipTableMap() {
        return internalGetMembershipTable().getMap();
      }
      /**
       * <code>map&lt;int32, .BrokerInfo&gt; membershipTable = 10;</code>
       */
      @java.lang.Override

      public model.Membership.BrokerInfo getMembershipTableOrDefault(
          int key,
          model.Membership.BrokerInfo defaultValue) {
        
        java.util.Map<java.lang.Integer, model.Membership.BrokerInfo> map =
            internalGetMembershipTable().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, .BrokerInfo&gt; membershipTable = 10;</code>
       */
      @java.lang.Override

      public model.Membership.BrokerInfo getMembershipTableOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, model.Membership.BrokerInfo> map =
            internalGetMembershipTable().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMembershipTable() {
        internalGetMutableMembershipTable().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int32, .BrokerInfo&gt; membershipTable = 10;</code>
       */

      public Builder removeMembershipTable(
          int key) {
        
        internalGetMutableMembershipTable().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, model.Membership.BrokerInfo>
      getMutableMembershipTable() {
        return internalGetMutableMembershipTable().getMutableMap();
      }
      /**
       * <code>map&lt;int32, .BrokerInfo&gt; membershipTable = 10;</code>
       */
      public Builder putMembershipTable(
          int key,
          model.Membership.BrokerInfo value) {
        
        if (value == null) {
  throw new NullPointerException("map value");
}

        internalGetMutableMembershipTable().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, .BrokerInfo&gt; membershipTable = 10;</code>
       */

      public Builder putAllMembershipTable(
          java.util.Map<java.lang.Integer, model.Membership.BrokerInfo> values) {
        internalGetMutableMembershipTable().getMutableMap()
            .putAll(values);
        return this;
      }

      private int version_ ;
      /**
       * <code>int32 version = 11;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>int32 version = 11;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 version = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MemberInfo)
    }

    // @@protoc_insertion_point(class_scope:MemberInfo)
    private static final model.Membership.MemberInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new model.Membership.MemberInfo();
    }

    public static model.Membership.MemberInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MemberInfo>
        PARSER = new com.google.protobuf.AbstractParser<MemberInfo>() {
      @java.lang.Override
      public MemberInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MemberInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MemberInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MemberInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public model.Membership.MemberInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BrokerInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BrokerInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string host = 1;</code>
     * @return The host.
     */
    java.lang.String getHost();
    /**
     * <code>string host = 1;</code>
     * @return The bytes for host.
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <code>int32 port = 2;</code>
     * @return The port.
     */
    int getPort();

    /**
     * <code>int32 leaderPort = 3;</code>
     * @return The leaderPort.
     */
    int getLeaderPort();

    /**
     * <code>int32 id = 4;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>int32 version = 5;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>bool isAlive = 6;</code>
     * @return The isAlive.
     */
    boolean getIsAlive();

    /**
     * <code>bool isLeader = 7;</code>
     * @return The isLeader.
     */
    boolean getIsLeader();
  }
  /**
   * Protobuf type {@code BrokerInfo}
   */
  public static final class BrokerInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BrokerInfo)
      BrokerInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BrokerInfo.newBuilder() to construct.
    private BrokerInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BrokerInfo() {
      host_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BrokerInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BrokerInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 16: {

              port_ = input.readInt32();
              break;
            }
            case 24: {

              leaderPort_ = input.readInt32();
              break;
            }
            case 32: {

              id_ = input.readInt32();
              break;
            }
            case 40: {

              version_ = input.readInt32();
              break;
            }
            case 48: {

              isAlive_ = input.readBool();
              break;
            }
            case 56: {

              isLeader_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return model.Membership.internal_static_BrokerInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return model.Membership.internal_static_BrokerInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              model.Membership.BrokerInfo.class, model.Membership.BrokerInfo.Builder.class);
    }

    public static final int HOST_FIELD_NUMBER = 1;
    private volatile java.lang.Object host_;
    /**
     * <code>string host = 1;</code>
     * @return The host.
     */
    @java.lang.Override
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <code>string host = 1;</code>
     * @return The bytes for host.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <code>int32 port = 2;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }

    public static final int LEADERPORT_FIELD_NUMBER = 3;
    private int leaderPort_;
    /**
     * <code>int32 leaderPort = 3;</code>
     * @return The leaderPort.
     */
    @java.lang.Override
    public int getLeaderPort() {
      return leaderPort_;
    }

    public static final int ID_FIELD_NUMBER = 4;
    private int id_;
    /**
     * <code>int32 id = 4;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int VERSION_FIELD_NUMBER = 5;
    private int version_;
    /**
     * <code>int32 version = 5;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    public static final int ISALIVE_FIELD_NUMBER = 6;
    private boolean isAlive_;
    /**
     * <code>bool isAlive = 6;</code>
     * @return The isAlive.
     */
    @java.lang.Override
    public boolean getIsAlive() {
      return isAlive_;
    }

    public static final int ISLEADER_FIELD_NUMBER = 7;
    private boolean isLeader_;
    /**
     * <code>bool isLeader = 7;</code>
     * @return The isLeader.
     */
    @java.lang.Override
    public boolean getIsLeader() {
      return isLeader_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(host_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, host_);
      }
      if (port_ != 0) {
        output.writeInt32(2, port_);
      }
      if (leaderPort_ != 0) {
        output.writeInt32(3, leaderPort_);
      }
      if (id_ != 0) {
        output.writeInt32(4, id_);
      }
      if (version_ != 0) {
        output.writeInt32(5, version_);
      }
      if (isAlive_ != false) {
        output.writeBool(6, isAlive_);
      }
      if (isLeader_ != false) {
        output.writeBool(7, isLeader_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(host_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, host_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, port_);
      }
      if (leaderPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, leaderPort_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, id_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, version_);
      }
      if (isAlive_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isAlive_);
      }
      if (isLeader_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, isLeader_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof model.Membership.BrokerInfo)) {
        return super.equals(obj);
      }
      model.Membership.BrokerInfo other = (model.Membership.BrokerInfo) obj;

      if (!getHost()
          .equals(other.getHost())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (getLeaderPort()
          != other.getLeaderPort()) return false;
      if (getId()
          != other.getId()) return false;
      if (getVersion()
          != other.getVersion()) return false;
      if (getIsAlive()
          != other.getIsAlive()) return false;
      if (getIsLeader()
          != other.getIsLeader()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + LEADERPORT_FIELD_NUMBER;
      hash = (53 * hash) + getLeaderPort();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + ISALIVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsAlive());
      hash = (37 * hash) + ISLEADER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsLeader());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static model.Membership.BrokerInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.Membership.BrokerInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.Membership.BrokerInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.Membership.BrokerInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.Membership.BrokerInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.Membership.BrokerInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.Membership.BrokerInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.Membership.BrokerInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static model.Membership.BrokerInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static model.Membership.BrokerInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static model.Membership.BrokerInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.Membership.BrokerInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(model.Membership.BrokerInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BrokerInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BrokerInfo)
        model.Membership.BrokerInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return model.Membership.internal_static_BrokerInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return model.Membership.internal_static_BrokerInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                model.Membership.BrokerInfo.class, model.Membership.BrokerInfo.Builder.class);
      }

      // Construct using model.Membership.BrokerInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        host_ = "";

        port_ = 0;

        leaderPort_ = 0;

        id_ = 0;

        version_ = 0;

        isAlive_ = false;

        isLeader_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return model.Membership.internal_static_BrokerInfo_descriptor;
      }

      @java.lang.Override
      public model.Membership.BrokerInfo getDefaultInstanceForType() {
        return model.Membership.BrokerInfo.getDefaultInstance();
      }

      @java.lang.Override
      public model.Membership.BrokerInfo build() {
        model.Membership.BrokerInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public model.Membership.BrokerInfo buildPartial() {
        model.Membership.BrokerInfo result = new model.Membership.BrokerInfo(this);
        result.host_ = host_;
        result.port_ = port_;
        result.leaderPort_ = leaderPort_;
        result.id_ = id_;
        result.version_ = version_;
        result.isAlive_ = isAlive_;
        result.isLeader_ = isLeader_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof model.Membership.BrokerInfo) {
          return mergeFrom((model.Membership.BrokerInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(model.Membership.BrokerInfo other) {
        if (other == model.Membership.BrokerInfo.getDefaultInstance()) return this;
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (other.getLeaderPort() != 0) {
          setLeaderPort(other.getLeaderPort());
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getIsAlive() != false) {
          setIsAlive(other.getIsAlive());
        }
        if (other.getIsLeader() != false) {
          setIsLeader(other.getIsLeader());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        model.Membership.BrokerInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (model.Membership.BrokerInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object host_ = "";
      /**
       * <code>string host = 1;</code>
       * @return The host.
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string host = 1;</code>
       * @return The bytes for host.
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string host = 1;</code>
       * @param value The host to set.
       * @return This builder for chaining.
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string host = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>string host = 1;</code>
       * @param value The bytes for host to set.
       * @return This builder for chaining.
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 2;</code>
       * @return The port.
       */
      @java.lang.Override
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 2;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private int leaderPort_ ;
      /**
       * <code>int32 leaderPort = 3;</code>
       * @return The leaderPort.
       */
      @java.lang.Override
      public int getLeaderPort() {
        return leaderPort_;
      }
      /**
       * <code>int32 leaderPort = 3;</code>
       * @param value The leaderPort to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderPort(int value) {
        
        leaderPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 leaderPort = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeaderPort() {
        
        leaderPort_ = 0;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 4;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 4;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>int32 version = 5;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>int32 version = 5;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 version = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private boolean isAlive_ ;
      /**
       * <code>bool isAlive = 6;</code>
       * @return The isAlive.
       */
      @java.lang.Override
      public boolean getIsAlive() {
        return isAlive_;
      }
      /**
       * <code>bool isAlive = 6;</code>
       * @param value The isAlive to set.
       * @return This builder for chaining.
       */
      public Builder setIsAlive(boolean value) {
        
        isAlive_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isAlive = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsAlive() {
        
        isAlive_ = false;
        onChanged();
        return this;
      }

      private boolean isLeader_ ;
      /**
       * <code>bool isLeader = 7;</code>
       * @return The isLeader.
       */
      @java.lang.Override
      public boolean getIsLeader() {
        return isLeader_;
      }
      /**
       * <code>bool isLeader = 7;</code>
       * @param value The isLeader to set.
       * @return This builder for chaining.
       */
      public Builder setIsLeader(boolean value) {
        
        isLeader_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isLeader = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsLeader() {
        
        isLeader_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BrokerInfo)
    }

    // @@protoc_insertion_point(class_scope:BrokerInfo)
    private static final model.Membership.BrokerInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new model.Membership.BrokerInfo();
    }

    public static model.Membership.BrokerInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BrokerInfo>
        PARSER = new com.google.protobuf.AbstractParser<BrokerInfo>() {
      @java.lang.Override
      public BrokerInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BrokerInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BrokerInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BrokerInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public model.Membership.BrokerInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MemberInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MemberInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MemberInfo_MembershipTableEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MemberInfo_MembershipTableEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BrokerInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BrokerInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027protos/membership.proto\"\236\003\n\nMemberInfo" +
      "\022\014\n\004host\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\022\n\n\002id\030\003 \001(\005" +
      "\022\020\n\010isLeader\030\004 \001(\010\022\r\n\005state\030\005 \001(\t\022\022\n\nlea" +
      "derHost\030\006 \001(\t\022\022\n\nleaderPort\030\007 \001(\005\022\017\n\007isA" +
      "live\030\010 \001(\010\022!\n\004type\030\t \001(\0162\023.MemberInfo.sr" +
      "cType\0229\n\017membershipTable\030\n \003(\0132 .MemberI" +
      "nfo.MembershipTableEntry\022\017\n\007version\030\013 \001(" +
      "\005\032C\n\024MembershipTableEntry\022\013\n\003key\030\001 \001(\005\022\032" +
      "\n\005value\030\002 \001(\0132\013.BrokerInfo:\0028\001\"Z\n\007srcTyp" +
      "e\022\014\n\010PRODUCER\020\000\022\n\n\006BROKER\020\001\022\014\n\010CONSUMER\020" +
      "\002\022\020\n\014LOADBALANCER\020\003\022\025\n\021CONSUMER_FOLLOWER" +
      "\020\004\"|\n\nBrokerInfo\022\014\n\004host\030\001 \001(\t\022\014\n\004port\030\002" +
      " \001(\005\022\022\n\nleaderPort\030\003 \001(\005\022\n\n\002id\030\004 \001(\005\022\017\n\007" +
      "version\030\005 \001(\005\022\017\n\007isAlive\030\006 \001(\010\022\020\n\010isLead" +
      "er\030\007 \001(\010B\023\n\005modelB\nMembershipb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MemberInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MemberInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MemberInfo_descriptor,
        new java.lang.String[] { "Host", "Port", "Id", "IsLeader", "State", "LeaderHost", "LeaderPort", "IsAlive", "Type", "MembershipTable", "Version", });
    internal_static_MemberInfo_MembershipTableEntry_descriptor =
      internal_static_MemberInfo_descriptor.getNestedTypes().get(0);
    internal_static_MemberInfo_MembershipTableEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MemberInfo_MembershipTableEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_BrokerInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BrokerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BrokerInfo_descriptor,
        new java.lang.String[] { "Host", "Port", "LeaderPort", "Id", "Version", "IsAlive", "IsLeader", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
