// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/msg.proto

package model;

public final class MsgInfo {
  private MsgInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Message.srcType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.Message.srcType type = 1;</code>
     * @return The type.
     */
    model.MsgInfo.Message.srcType getType();

    /**
     * <code>string srcId = 2;</code>
     * @return The srcId.
     */
    java.lang.String getSrcId();
    /**
     * <code>string srcId = 2;</code>
     * @return The bytes for srcId.
     */
    com.google.protobuf.ByteString
        getSrcIdBytes();

    /**
     * <code>string topic = 3;</code>
     * @return The topic.
     */
    java.lang.String getTopic();
    /**
     * <code>string topic = 3;</code>
     * @return The bytes for topic.
     */
    com.google.protobuf.ByteString
        getTopicBytes();

    /**
     * <code>bytes data = 4;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>int32 offset = 5;</code>
     * @return The offset.
     */
    int getOffset();

    /**
     * <code>int32 startingPosition = 6;</code>
     * @return The startingPosition.
     */
    int getStartingPosition();

    /**
     * <code>int32 msgId = 8;</code>
     * @return The msgId.
     */
    int getMsgId();

    /**
     * <code>int32 id = 9;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>bool isSnapshot = 10;</code>
     * @return The isSnapshot.
     */
    boolean getIsSnapshot();
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      type_ = 0;
      srcId_ = "";
      topic_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              srcId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              topic_ = s;
              break;
            }
            case 34: {

              data_ = input.readBytes();
              break;
            }
            case 40: {

              offset_ = input.readInt32();
              break;
            }
            case 48: {

              startingPosition_ = input.readInt32();
              break;
            }
            case 64: {

              msgId_ = input.readInt32();
              break;
            }
            case 72: {

              id_ = input.readInt32();
              break;
            }
            case 80: {

              isSnapshot_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return model.MsgInfo.internal_static_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return model.MsgInfo.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              model.MsgInfo.Message.class, model.MsgInfo.Message.Builder.class);
    }

    /**
     * Protobuf enum {@code Message.srcType}
     */
    public enum srcType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PRODUCER = 0;</code>
       */
      PRODUCER(0),
      /**
       * <code>BROKER = 1;</code>
       */
      BROKER(1),
      /**
       * <code>CONSUMER = 2;</code>
       */
      CONSUMER(2),
      /**
       * <code>ACK = 3;</code>
       */
      ACK(3),
      /**
       * <code>SNAPSHOT = 4;</code>
       */
      SNAPSHOT(4),
      /**
       * <code>SUBSCRIBER = 5;</code>
       */
      SUBSCRIBER(5),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>PRODUCER = 0;</code>
       */
      public static final int PRODUCER_VALUE = 0;
      /**
       * <code>BROKER = 1;</code>
       */
      public static final int BROKER_VALUE = 1;
      /**
       * <code>CONSUMER = 2;</code>
       */
      public static final int CONSUMER_VALUE = 2;
      /**
       * <code>ACK = 3;</code>
       */
      public static final int ACK_VALUE = 3;
      /**
       * <code>SNAPSHOT = 4;</code>
       */
      public static final int SNAPSHOT_VALUE = 4;
      /**
       * <code>SUBSCRIBER = 5;</code>
       */
      public static final int SUBSCRIBER_VALUE = 5;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static srcType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static srcType forNumber(int value) {
        switch (value) {
          case 0: return PRODUCER;
          case 1: return BROKER;
          case 2: return CONSUMER;
          case 3: return ACK;
          case 4: return SNAPSHOT;
          case 5: return SUBSCRIBER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<srcType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          srcType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<srcType>() {
              public srcType findValueByNumber(int number) {
                return srcType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return model.MsgInfo.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final srcType[] VALUES = values();

      public static srcType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private srcType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Message.srcType)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.Message.srcType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.Message.srcType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public model.MsgInfo.Message.srcType getType() {
      @SuppressWarnings("deprecation")
      model.MsgInfo.Message.srcType result = model.MsgInfo.Message.srcType.valueOf(type_);
      return result == null ? model.MsgInfo.Message.srcType.UNRECOGNIZED : result;
    }

    public static final int SRCID_FIELD_NUMBER = 2;
    private volatile java.lang.Object srcId_;
    /**
     * <code>string srcId = 2;</code>
     * @return The srcId.
     */
    @java.lang.Override
    public java.lang.String getSrcId() {
      java.lang.Object ref = srcId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        srcId_ = s;
        return s;
      }
    }
    /**
     * <code>string srcId = 2;</code>
     * @return The bytes for srcId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSrcIdBytes() {
      java.lang.Object ref = srcId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        srcId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOPIC_FIELD_NUMBER = 3;
    private volatile java.lang.Object topic_;
    /**
     * <code>string topic = 3;</code>
     * @return The topic.
     */
    @java.lang.Override
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      }
    }
    /**
     * <code>string topic = 3;</code>
     * @return The bytes for topic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 4;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int OFFSET_FIELD_NUMBER = 5;
    private int offset_;
    /**
     * <code>int32 offset = 5;</code>
     * @return The offset.
     */
    @java.lang.Override
    public int getOffset() {
      return offset_;
    }

    public static final int STARTINGPOSITION_FIELD_NUMBER = 6;
    private int startingPosition_;
    /**
     * <code>int32 startingPosition = 6;</code>
     * @return The startingPosition.
     */
    @java.lang.Override
    public int getStartingPosition() {
      return startingPosition_;
    }

    public static final int MSGID_FIELD_NUMBER = 8;
    private int msgId_;
    /**
     * <code>int32 msgId = 8;</code>
     * @return The msgId.
     */
    @java.lang.Override
    public int getMsgId() {
      return msgId_;
    }

    public static final int ID_FIELD_NUMBER = 9;
    private int id_;
    /**
     * <code>int32 id = 9;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int ISSNAPSHOT_FIELD_NUMBER = 10;
    private boolean isSnapshot_;
    /**
     * <code>bool isSnapshot = 10;</code>
     * @return The isSnapshot.
     */
    @java.lang.Override
    public boolean getIsSnapshot() {
      return isSnapshot_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != model.MsgInfo.Message.srcType.PRODUCER.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(srcId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, srcId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, topic_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(4, data_);
      }
      if (offset_ != 0) {
        output.writeInt32(5, offset_);
      }
      if (startingPosition_ != 0) {
        output.writeInt32(6, startingPosition_);
      }
      if (msgId_ != 0) {
        output.writeInt32(8, msgId_);
      }
      if (id_ != 0) {
        output.writeInt32(9, id_);
      }
      if (isSnapshot_ != false) {
        output.writeBool(10, isSnapshot_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != model.MsgInfo.Message.srcType.PRODUCER.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(srcId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, srcId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, topic_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      if (offset_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, offset_);
      }
      if (startingPosition_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, startingPosition_);
      }
      if (msgId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, msgId_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, id_);
      }
      if (isSnapshot_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, isSnapshot_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof model.MsgInfo.Message)) {
        return super.equals(obj);
      }
      model.MsgInfo.Message other = (model.MsgInfo.Message) obj;

      if (type_ != other.type_) return false;
      if (!getSrcId()
          .equals(other.getSrcId())) return false;
      if (!getTopic()
          .equals(other.getTopic())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (getOffset()
          != other.getOffset()) return false;
      if (getStartingPosition()
          != other.getStartingPosition()) return false;
      if (getMsgId()
          != other.getMsgId()) return false;
      if (getId()
          != other.getId()) return false;
      if (getIsSnapshot()
          != other.getIsSnapshot()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + SRCID_FIELD_NUMBER;
      hash = (53 * hash) + getSrcId().hashCode();
      hash = (37 * hash) + TOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getTopic().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + getOffset();
      hash = (37 * hash) + STARTINGPOSITION_FIELD_NUMBER;
      hash = (53 * hash) + getStartingPosition();
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgId();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + ISSNAPSHOT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsSnapshot());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static model.MsgInfo.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.MsgInfo.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.MsgInfo.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.MsgInfo.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.MsgInfo.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.MsgInfo.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.MsgInfo.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.MsgInfo.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static model.MsgInfo.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static model.MsgInfo.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static model.MsgInfo.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.MsgInfo.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(model.MsgInfo.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        model.MsgInfo.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return model.MsgInfo.internal_static_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return model.MsgInfo.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                model.MsgInfo.Message.class, model.MsgInfo.Message.Builder.class);
      }

      // Construct using model.MsgInfo.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        srcId_ = "";

        topic_ = "";

        data_ = com.google.protobuf.ByteString.EMPTY;

        offset_ = 0;

        startingPosition_ = 0;

        msgId_ = 0;

        id_ = 0;

        isSnapshot_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return model.MsgInfo.internal_static_Message_descriptor;
      }

      @java.lang.Override
      public model.MsgInfo.Message getDefaultInstanceForType() {
        return model.MsgInfo.Message.getDefaultInstance();
      }

      @java.lang.Override
      public model.MsgInfo.Message build() {
        model.MsgInfo.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public model.MsgInfo.Message buildPartial() {
        model.MsgInfo.Message result = new model.MsgInfo.Message(this);
        result.type_ = type_;
        result.srcId_ = srcId_;
        result.topic_ = topic_;
        result.data_ = data_;
        result.offset_ = offset_;
        result.startingPosition_ = startingPosition_;
        result.msgId_ = msgId_;
        result.id_ = id_;
        result.isSnapshot_ = isSnapshot_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof model.MsgInfo.Message) {
          return mergeFrom((model.MsgInfo.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(model.MsgInfo.Message other) {
        if (other == model.MsgInfo.Message.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getSrcId().isEmpty()) {
          srcId_ = other.srcId_;
          onChanged();
        }
        if (!other.getTopic().isEmpty()) {
          topic_ = other.topic_;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getOffset() != 0) {
          setOffset(other.getOffset());
        }
        if (other.getStartingPosition() != 0) {
          setStartingPosition(other.getStartingPosition());
        }
        if (other.getMsgId() != 0) {
          setMsgId(other.getMsgId());
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getIsSnapshot() != false) {
          setIsSnapshot(other.getIsSnapshot());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        model.MsgInfo.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (model.MsgInfo.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.Message.srcType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.Message.srcType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Message.srcType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public model.MsgInfo.Message.srcType getType() {
        @SuppressWarnings("deprecation")
        model.MsgInfo.Message.srcType result = model.MsgInfo.Message.srcType.valueOf(type_);
        return result == null ? model.MsgInfo.Message.srcType.UNRECOGNIZED : result;
      }
      /**
       * <code>.Message.srcType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(model.MsgInfo.Message.srcType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Message.srcType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object srcId_ = "";
      /**
       * <code>string srcId = 2;</code>
       * @return The srcId.
       */
      public java.lang.String getSrcId() {
        java.lang.Object ref = srcId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          srcId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string srcId = 2;</code>
       * @return The bytes for srcId.
       */
      public com.google.protobuf.ByteString
          getSrcIdBytes() {
        java.lang.Object ref = srcId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          srcId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string srcId = 2;</code>
       * @param value The srcId to set.
       * @return This builder for chaining.
       */
      public Builder setSrcId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        srcId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string srcId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSrcId() {
        
        srcId_ = getDefaultInstance().getSrcId();
        onChanged();
        return this;
      }
      /**
       * <code>string srcId = 2;</code>
       * @param value The bytes for srcId to set.
       * @return This builder for chaining.
       */
      public Builder setSrcIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        srcId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object topic_ = "";
      /**
       * <code>string topic = 3;</code>
       * @return The topic.
       */
      public java.lang.String getTopic() {
        java.lang.Object ref = topic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          topic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string topic = 3;</code>
       * @return The bytes for topic.
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        java.lang.Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string topic = 3;</code>
       * @param value The topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopic() {
        
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 3;</code>
       * @param value The bytes for topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        topic_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 4;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 4;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private int offset_ ;
      /**
       * <code>int32 offset = 5;</code>
       * @return The offset.
       */
      @java.lang.Override
      public int getOffset() {
        return offset_;
      }
      /**
       * <code>int32 offset = 5;</code>
       * @param value The offset to set.
       * @return This builder for chaining.
       */
      public Builder setOffset(int value) {
        
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 offset = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearOffset() {
        
        offset_ = 0;
        onChanged();
        return this;
      }

      private int startingPosition_ ;
      /**
       * <code>int32 startingPosition = 6;</code>
       * @return The startingPosition.
       */
      @java.lang.Override
      public int getStartingPosition() {
        return startingPosition_;
      }
      /**
       * <code>int32 startingPosition = 6;</code>
       * @param value The startingPosition to set.
       * @return This builder for chaining.
       */
      public Builder setStartingPosition(int value) {
        
        startingPosition_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 startingPosition = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartingPosition() {
        
        startingPosition_ = 0;
        onChanged();
        return this;
      }

      private int msgId_ ;
      /**
       * <code>int32 msgId = 8;</code>
       * @return The msgId.
       */
      @java.lang.Override
      public int getMsgId() {
        return msgId_;
      }
      /**
       * <code>int32 msgId = 8;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(int value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 msgId = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        
        msgId_ = 0;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 9;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 9;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private boolean isSnapshot_ ;
      /**
       * <code>bool isSnapshot = 10;</code>
       * @return The isSnapshot.
       */
      @java.lang.Override
      public boolean getIsSnapshot() {
        return isSnapshot_;
      }
      /**
       * <code>bool isSnapshot = 10;</code>
       * @param value The isSnapshot to set.
       * @return This builder for chaining.
       */
      public Builder setIsSnapshot(boolean value) {
        
        isSnapshot_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isSnapshot = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsSnapshot() {
        
        isSnapshot_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final model.MsgInfo.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new model.MsgInfo.Message();
    }

    public static model.MsgInfo.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public model.MsgInfo.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020protos/msg.proto\"\210\002\n\007Message\022\036\n\004type\030\001" +
      " \001(\0162\020.Message.srcType\022\r\n\005srcId\030\002 \001(\t\022\r\n" +
      "\005topic\030\003 \001(\t\022\014\n\004data\030\004 \001(\014\022\016\n\006offset\030\005 \001" +
      "(\005\022\030\n\020startingPosition\030\006 \001(\005\022\r\n\005msgId\030\010 " +
      "\001(\005\022\n\n\002id\030\t \001(\005\022\022\n\nisSnapshot\030\n \001(\010\"X\n\007s" +
      "rcType\022\014\n\010PRODUCER\020\000\022\n\n\006BROKER\020\001\022\014\n\010CONS" +
      "UMER\020\002\022\007\n\003ACK\020\003\022\014\n\010SNAPSHOT\020\004\022\016\n\nSUBSCRI" +
      "BER\020\005B\020\n\005modelB\007MsgInfob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "Type", "SrcId", "Topic", "Data", "Offset", "StartingPosition", "MsgId", "Id", "IsSnapshot", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
